List<Map<String, dynamic>> travelLogData = [
  {
    'logName': 'Check In',
    'logId': 'VHMV+F6C',
    'phone': 'Redmi 6',
    'battery': '99%',
    'startTime': '11:00',
    'endTime': '11:30',
  },
  {
    'logName': 'Arravinthan Electricals',
    'logId': 'RPMV+633',
    'phone': 'Redmi 6',
    'battery': '92%',
    'startTime': '12:00',
    'endTime': '12:30',
  },
  {
    'logName': 'Mothakkada Electricals',
    'logId': 'VPX8+P8X',
    'phone': 'Redmi 6',
    'battery': '89%',
    'startTime': '13:00',
    'endTime': '13:30',
  },
  {
    'logName': 'Aryan Electricals',
    'logId': 'YFKU+F6C',
    'phone': 'Redmi 6',
    'battery': '75%',
    'startTime': '14:00',
    'endTime': '14:30',
  },
  {
    'logName': 'Sabeel Traders',
    'logId': 'DGJ+F6C',
    'phone': 'Redmi 6',
    'battery': '65%',
    'startTime': '15:00',
    'endTime': '15:30',
  },
  {
    'logName': 'Abc Steels',
    'logId': 'CFHJ+F6HC',
    'phone': 'Redmi 6',
    'battery': '50%',
    'startTime': '16:00',
    'endTime': '16:30',
  },
];
